source $HOME/.config/nvim/plugins.vim
source $HOME/.config/nvim/settings.vim
source $HOME/.config/nvim/airline.vim
source $HOME/.config/nvim/fzf.vim
source $HOME/.config/nvim/coc.vim
source $HOME/.config/nvim/quick-scope.vim
source $HOME/.config/nvim/start-screen.vim
source $HOME/.config/nvim/gruvbox.vim
source $HOME/.config/nvim/rainbow-parentheses.vim
source $HOME/.config/nvim/syntastic.vim
source $HOME/.config/nvim/gutentags.vim
source $HOME/.config/nvim/emoji.vim
