source $HOME/Developer/personalConfigs/nvim/plugings.vim
source $HOME/Developer/personalConfigs/nvim/personal.vim
source $HOME/Developer/personalConfigs/nvim/colors.vim
source $HOME/Developer/personalConfigs/nvim/mappings.vim
source $HOME/Developer/personalConfigs/nvim/buftabline.vim
source $HOME/Developer/personalConfigs/nvim/telescope.vim
source $HOME/Developer/personalConfigs/nvim/express_line.vim
source $HOME/Developer/personalConfigs/nvim/vue.vim
source $HOME/Developer/personalConfigs/nvim/nvim_tree.vim
