set cursorline
set relativenumber
set hidden
set noerrorbells
set expandtab
set ts=2
set sw=2
set sts=2
set smartindent
set nu
set nowrap
set smartcase
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch
set termguicolors
set scrolloff=8
set completeopt=menuone,noinsert,noselect
set colorcolumn=130
set signcolumn=yes
set cmdheight=2
set updatetime=50
set shortmess+=c
